# Generated by Django 4.2.7 on 2024-01-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avocat', '0005_alter_avocat_carteindent_alter_avocat_cartepro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avocat',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
