# Generated by Django 4.2.7 on 2024-01-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avocat', '0006_alter_avocat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avocat',
            name='password',
        ),
    ]
